### ISSUE TITLE
Editor height should have a soft limit

### ISSUE THREAD

**Issue by joaomoreno** [hediet/chrome-ext-github-monaco#4]
When editing a large comment post or wiki page, the editor takes the same height as its content. This is problematic because the users can't scroll inside the editor area, not can they click and drag text selection to scroll down.

I suggest to just cap the editor widget height, like GH normally does. What do you think?

![recording (2)](https://user-images.githubusercontent.com/22350/101882976-78311280-3b4b-11eb-87f6-b3e15fcc5258.gif)

**Comment by hediet** [comment]
> I suggest to just cap the editor widget height, like GH normally does. What do you think?

A good idea! Should be easy to implement, I will have a look in the next days.
At first it was kind of a feature, but I totally see why it does not make sense in your case.
Maybe a setting would make sense here.

**Comment by hediet** [comment]
There is a soft limit of 400px now:
![image](https://user-images.githubusercontent.com/2931520/101986888-1975b100-3c91-11eb-9e2f-5b8beef6da9c.png)

I also added a full screen (aka zen) mode that can be toggled with F11:
![image](https://user-images.githubusercontent.com/2931520/101986949-71141c80-3c91-11eb-81bd-2dd3322078ab.png)

**Comment by joaomoreno** [comment]
That is fantastic! Definitely gonna demo this in today's standup! 👏

**Comment by hediet** [comment]
> That is fantastic! Definitely gonna demo this in today's standup! 👏

Thanks, I hope they liked it 😊
